# Generated by Django 5.0.3 on 2024-03-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_commands_command_alter_command_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Фото')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('job', models.CharField(max_length=100, verbose_name='Должность')),
                ('instagram', models.URLField(verbose_name='Инстаграм')),
                ('github', models.URLField(verbose_name='GitHub')),
                ('facebook', models.URLField(verbose_name='Фейсбук')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл.почта')),
            ],
            options={
                'verbose_name_plural': 'Наша команда',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл.почта')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефонный номер')),
                ('adress', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Фото')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
