# Generated by Django 5.0.3 on 2024-03-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_command_img_alter_about_img_alter_about_img2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='description',
        ),
    ]
