# Generated by Django 5.0.3 on 2024-03-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_command_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефонный номер')),
                ('about', models.TextField(verbose_name='Описание')),
                ('adress', models.CharField(max_length=255, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл.почта')),
                ('instagram', models.URLField(verbose_name='Instagram')),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('youtube', models.URLField(verbose_name='YouTube')),
            ],
            options={
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонный номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('childs', models.CharField(max_length=255, verbose_name='Дети')),
                ('adults', models.CharField(max_length=255, verbose_name='Взрослые')),
            ],
            options={
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
