# Generated by Django 5.0.3 on 2024-03-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_footer_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='adults',
            field=models.IntegerField(max_length=255, verbose_name='Взрослые'),
        ),
        migrations.AlterField(
            model_name='post',
            name='childs',
            field=models.IntegerField(verbose_name='Дети'),
        ),
    ]
