# Generated by Django 5.0.3 on 2024-03-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_post_adults_alter_post_childs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='adults',
            field=models.IntegerField(verbose_name='Взрослые'),
        ),
    ]
