# Generated by Django 5.0.3 on 2024-03-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_post_adults'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='full_name',
            new_name='fullname',
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.CharField(max_length=255, verbose_name='Дата'),
        ),
    ]
