# Generated by Django 5.0.3 on 2024-03-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок о видео'),
        ),
    ]
