# Generated by Django 5.0.3 on 2024-03-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_news_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image_2',
        ),
        migrations.AddField(
            model_name='banner',
            name='title_for_video',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок о видео'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
