# Generated by Django 5.0.3 on 2024-03-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_news_news_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_item',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
