# Generated by Django 5.0.3 on 2024-03-30 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_facilties_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facilties',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
